set(CMAKE_MACOSX_BUNDLE YES)
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED NO)

if (CMAKE_TARGET_ARCHITECTURE MATCHES "arm64")
  set(CMAKE_OSX_SYSROOT iphoneos)
else()
  set(CMAKE_OSX_SYSROOT iphonesimulator)
endif()

set(CMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET 10.0)

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
